name: build

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:
  pull_request:

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1
  
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/vanilla-os/pico:main
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it

    steps:
    - uses: actions/checkout@v4

    - name: De-bloat stock image
      run: |
        rm -r /run/host/usr/share/dotnet
        rm -r /run/host${{ runner.tool_cache }}

    - name: Install needed packages
      run: apt update && apt install dpkg-dev build-essential debhelper python3 meson libadwaita-1-dev libgnome-desktop-4-dev libgweather-4-dev gettext desktop-file-utils make libjpeg-dev libnm-dev libnma-dev libnma-gtk4-dev -y

# ... (other steps)

    - name: Create output directory
      run: mkdir -p ./build-output

    - name: Build debian package
      run: |
        dpkg-buildpackage --no-sign --build-dir=./build-output
        mv ./build-output/*.deb ./build-output/vanilla-installer.deb

    - uses: softprops/action-gh-release@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "continuous_mate"
        prerelease: true
        name: "Continuous Build"
        files: |
          ./build-output/vanilla-installer.deb

